version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: motion-backend
    ports:
      - "8000:8080"

  frontend:
    build:
      context: ./frontend
    container_name: motion-frontend
    ports:
      - "8501:8080"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend




